services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - webnet
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    #   - ./certs:/etc/letsencrypt
    #   - ./certs-data:/data/letsencrypt
    networks:
      - webnet

networks:
  webnet: