services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - memoires-vives_webnet

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: SecurePasswordV3rySécure
      MYSQL_DATABASE: mv_db
      MYSQL_USER: bdd_user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - memoires-vives_webnet

  springboot-app:
    build:
      context: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mv_db
      SPRING_DATASOURCE_USERNAME: bdd_user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - mysql
    networks:
      - memoires-vives_webnet

volumes:
  mysql-data:

networks:
  webnet:
    driver: bridge