services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: SecurePasswordV3rySécure
      MYSQL_DATABASE: mv_db
      MYSQL_USER: bdd_user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - webnet

  springboot-app:
    image: docker.io/opyms/memoires-vives:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    depends_on:
      - mysql
    networks:
      - webnet

volumes:
  mysql-data:

networks:
  webnet:
    driver: bridge