services:
  nginx:
    image: nginx:1.27.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      # - images-data:/usr/share/nginx/html/images/public
    networks:
      - webnet

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - webnet

  springboot-app:
    image: docker.io/opyms/memoires-vives:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    # volumes:
    #   - images-data:/app/static/images/public
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - webnet
    command: ["java", "-jar", "/app/memoires-vives.jar", "-Dspring.profiles.active=prod"]


volumes:
  mysql-data:
  # images-data:

networks:
  webnet:
    driver: bridge