name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build JAR with Gradle
      run: |
        cd workspace/springboot-app
        ./gradlew build

    - name: Commit JAR to repository
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/OpymS/memoires-vives.git
        git add -f workspace/springboot-app/build/libs/memoires-vives.jar
        git commit -m "Add built JAR file"
        git push origin main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -p 55222 ubuntu@51.77.140.10 << 'EOF'
        cd /home/ubuntu/docker/memoires-vives
        git pull origin main
        docker compose down
        docker compose up --build -d
        EOF