name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -p 55222 ubuntu@51.77.140.10 << 'EOF'
        cd /home/ubuntu/docker/memoires-vives
        git pull origin main
        cd workspace/springboot-app
        ./gradlew build
        cd ../..
        docker compose down
        docker compose up --build -d
        EOF