name: Build and deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build JAR with Gradle
      run: |
        cd workspace/springboot-app
        ./gradlew build

    - name: Build Docker image
      run: |
        docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/memoires-vives:latest .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/memoires-vives:latest

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p 55222 ubuntu@51.77.140.10 << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
          docker pull opyms/memoires-vives:latest
          docker compose -f /home/ubuntu/docker/memoires-vives/docker-compose.yml down
          docker compose -f /home/ubuntu/docker/memoires-vives/docker-compose.yml up -d
          EOF